name: CI
on:
  repository_dispatch:
    types:
      - webhook-1
      - webhook-2
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
jobs:
  msw-msvs:
    runs-on: windows-${{ matrix.vsversion }}
    name: wxMSW vs${{ matrix.vsversion }} ${{ matrix.configuration }} ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration: 'Debug'
            platform: 'Win32'
            vsversion: 2019
          # - configuration: 'Release'
          #   platform: 'Win32'
          #   vsversion: 2019
          # - configuration: 'Debug'
          #   platform: 'x64'
          #   vsversion: 2019
          # - configuration: 'Release'
          #   platform: 'x64'
          #   vsversion: 2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure build options
        working-directory: include/wx/msw
        run: |
            $use_utf8 = "${{ matrix.use_utf8 }}" ? 1 : 0
            if ( $use_utf8 ) {
              $txt = Get-Content setup.h
              Write-Output $txt |
              %{$_ -replace "define wxUSE_UNICODE_UTF8 0", "define wxUSE_UNICODE_UTF8 $use_utf8"} |
              Set-Content setup.h
            }
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
            vs-prerelease: true

      - name: Build
        run: |
            msbuild /noLogo /m '/p:Configuration=${{ matrix.configuration }}' /p:Platform=${{ matrix.platform }} build\msw\wx_vc16.sln
            if ( '${{ matrix.configuration }}'.IndexOf('DLL') -ne -1 ) {
                $dlldir = Join-Path (Get-Location) 'lib\vc_${{ matrix.platform }}_dll'
                Write-Output "Adding $dlldir to the PATH"
                $dlldir | Out-File -Append $env:GITHUB_PATH
            }
      - name: Package Debug files (Win32)
        if: matrix.configuration == 'Debug' && matrix.platform == 'Win32'
        run: |
          mkdir -p package
          mv ./include ./package/
          mv ./lib/vc_lib ./package/
      - name: Upload Debug artifact (Win32)
        if: matrix.configuration == 'Debug' && matrix.platform == 'Win32'
        uses: actions/upload-artifact@v4
        with:
          name: vc_lib_dbg_win32
          path: package

      - name: Package Release files (Win32)
        if: matrix.configuration == 'Release' && matrix.platform == 'Win32'
        run: |
          mkdir -p package
          mv ./include ./package/
          mv ./lib/vc_lib ./package/
      - name: Upload Release artifact (Win32)
        if: matrix.configuration == 'Release' && matrix.platform == 'Win32'
        uses: actions/upload-artifact@v4
        with:
          name: vc_lib_rel_win32
          path: package

      - name: Package Debug files (x64)
        if: matrix.configuration == 'Debug' && matrix.platform == 'x64'
        run: |
          mkdir -p package
          mv ./include ./package/
          mv ./lib/vc_x64_lib ./package/
      - name: Upload Debug artifact (x64)
        if: matrix.configuration == 'Debug' && matrix.platform == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: vc_lib_dbg_x64
          path: package

      - name: Package Release files (x64)
        if: matrix.configuration == 'Release' && matrix.platform == 'x64'
        run: |
          mkdir -p package
          mv ./include ./package/
          mv ./lib/vc_x64_lib ./package/
      - name: Upload Release artifact (x64)
        if: matrix.configuration == 'Release' && matrix.platform == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: vc_lib_rel_x64
          path: package

  create-release:
    runs-on: ubuntu-latest
    needs: msw-msvs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - name: Install GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        
      - name: Delete existing release
        run: gh release delete $RELEASE_DATE --yes || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release
        run: gh release create $RELEASE_DATE -t "Release $RELEASE_DATE" -n "Automated release for $RELEASE_DATE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload Artifacts to Release
        run: |
          gh release upload $RELEASE_DATE ./artifacts/vc_lib_dbg_win32.zip
          gh release upload $RELEASE_DATE ./artifacts/vc_lib_rel_win32.zip
          gh release upload $RELEASE_DATE ./artifacts/vc_lib_dbg_x64.zip
          gh release upload $RELEASE_DATE ./artifacts/vc_lib_rel_x64.zip
