name: CI
on:
  repository_dispatch:
    types:
      - webhook-1
      - webhook-2
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
jobs:
  msw-msvs:
    runs-on: windows-${{ matrix.vsversion }}
    name: wxMSW vs${{ matrix.vsversion }} ${{ matrix.configuration }} ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration: 'Debug'
            platform: 'Win32'
            vsversion: 2019
          - configuration: 'Release'
            platform: 'Win32'
            vsversion: 2019
          # - configuration: 'Debug'
          #   platform: 'x64'
          #   vsversion: 2019
          # - configuration: 'Release'
          #   platform: 'x64'
          #   vsversion: 2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure build options
        working-directory: include/wx/msw
        run: |
            $use_utf8 = "${{ matrix.use_utf8 }}" ? 1 : 0
            if ( $use_utf8 ) {
              $txt = Get-Content setup.h
              Write-Output $txt |
              %{$_ -replace "define wxUSE_UNICODE_UTF8 0", "define wxUSE_UNICODE_UTF8 $use_utf8"} |
              Set-Content setup.h
            }

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
            vs-prerelease: true

      - name: Build
        run: |
            msbuild /noLogo /m '/p:Configuration=${{ matrix.configuration }}' /p:Platform=${{ matrix.platform }} build\msw\wx_vc16.sln
            if ( '${{ matrix.configuration }}'.IndexOf('DLL') -ne -1 ) {
                $dlldir = Join-Path (Get-Location) 'lib\vc_${{ matrix.platform }}_dll'
                Write-Output "Adding $dlldir to the PATH"
                $dlldir | Out-File -Append $env:GITHUB_PATH
            }
      - name: Package files
        if: matrix.configuration == 'Debug' && matrix.platform == 'Win32'
        run: |
            mkdir -p package
            cp ./lib/vc_lib/xxd.lib ./package/
            cp ./lib/vc_lib/xxd.pdb ./package/
            zip -r vc_lib_dbg.zip package/
      
      - name: Package files
        if: matrix.configuration == 'Release' && matrix.platform == 'Win32'
        run: |
            mkdir -p package
            cp ./lib/vc_lib/xx.lib ./package/
            cp ./lib/vc_lib/xx.pdb ./package/
            zip -r vc_lib_rel.zip package/
      
      - name: Upload artifact (Debug)
        if: matrix.configuration == 'Debug' && matrix.platform == 'Win32'
        uses: actions/upload-artifact@v2
        with:
          name: vc_lib_dbg.zip
          path: vc_lib_dbg.zip
      
      - name: Upload artifact (Release)
        if: matrix.configuration == 'Release' && matrix.platform == 'Win32'
        uses: actions/upload-artifact@v2
        with:
          name: vc_lib_rel.zip
          path: vc_lib_rel.zip

